apiVersion: apps/v1
kind: Deployment
metadata:
  name: finance-service
  labels:
    app: finance-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: finance-service
  template:
    metadata:
      labels:
        app: finance-service
    spec:
      containers:
      - name: finance-service
        image: finance-service:v1
        imagePullPolicy: Never
        ports:
        - containerPort: 3002
        env:
        - name: NODE_ENV
          value: "production"
---
apiVersion: v1
kind: Service
metadata:
  name: finance-service
spec:
  selector:
    app: finance-service
  ports:
    - port: 80
      targetPort: 3002
  type: ClusterIP